/** The column order of the merchant's WooCommerce Customer/Order CSV export. */
export const wooOrderColumns = [
  ['orderNumber', 'Order Number'],
  ['orderStatus', 'Order Status'],
  ['orderDate', 'Order Date'],
  ['customerNote', 'Customer Note'],
  ['billingFirstName', 'First Name (Billing)'],
  ['billingLastName', 'Last Name (Billing)'],
  ['billingCompany', 'Company (Billing)'],
  ['billingAddress', 'Address 1&2 (Billing)'],
  ['billingCity', 'City (Billing)'],
  ['billingState', 'State Code (Billing)'],
  ['billingStateName', 'Governorate (Billing)'],
  ['billingPostcode', 'Postcode (Billing)'],
  ['billingCountry', 'Country Code (Billing)'],
  ['billingEmail', 'Email (Billing)'],
  ['billingPhone', 'Phone (Billing)'],
  ['shippingFirstName', 'First Name (Shipping)'],
  ['shippingLastName', 'Last Name (Shipping)'],
  ['shippingAddress', 'Address 1&2 (Shipping)'],
  ['shippingCity', 'City (Shipping)'],
  ['shippingState', 'State Code (Shipping)'],
  ['shippingStateName', 'Governorate (Shipping)'],
  ['shippingPostcode', 'Postcode (Shipping)'],
  ['shippingCountry', 'Country Code (Shipping)'],
  ['paymentTitle', 'Payment Method Title'],
  ['cartDiscount', 'Cart Discount Amount'],
  ['cartDiscountInclTax', 'Cart Discount Amount(inc. tax)'],
  ['orderSubtotal', 'Order Subtotal Amount'],
  ['shippingTitle', 'Shipping Method Title'],
  ['shippingAmount', 'Order Shipping Amount'],
  ['refundAmount', 'Order Refund Amount'],
  ['orderTotal', 'Order Total Amount'],
  ['orderTax', 'Order Total Tax Amount'],
  ['sku', 'SKU'],
  ['itemNumber', 'Item #'],
  ['itemName', 'Item Name'],
  ['quantity', 'Quantity (- Refund)'],
  ['itemCost', 'Item Cost'],
  ['couponCode', 'Coupon Code'],
  ['discountAmount', 'Discount Amount'],
  ['discountTax', 'Discount Amount Tax'],
] as const;

export const wooOrderExportColumns = wooOrderColumns.map(([key, label]) => ({
  key: `woo.${key}`,
  label,
  type: 'text' as const,
}));
